[package]
name = "solarhorizon/rodux-utils"
description = "A collection of utilities for use with Rodux"
authors = ["SolarHorizon"]
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
Immut = "solarhorizon/immut@0.2.1"
